name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Rafael Alejandro
      - APELLIDO=Putaro
      - DOCUMENTO=29752645
      - NACIMIENTO=1982-08-28
      - NUMERO=2233
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Carlos Omar
      - APELLIDO=Pugliese
      - DOCUMENTO=26321515
      - NACIMIENTO=1970-10-05
      - NUMERO=4123
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Pedro Daniel
      - APELLIDO=Alcantara
      - DOCUMENTO=33762888
      - NACIMIENTO=1990-01-05
      - NUMERO=8429
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Marco
      - APELLIDO=Di Palma
      - DOCUMENTO=33762888
      - NACIMIENTO=1975-01-23
      - NUMERO=1506
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
